slice_name: "\U0001F4CA Distribution of RFM scores"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 28__table
  viz_type: echarts_timeseries_bar
  x_axis: RFM_Score
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Customer ID
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 796
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DOUBLE PRECISION
      type_generic: 0
      uuid: 75432ce5-0b00-4efa-b993-b6e2a028217b
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT(Customer ID)
    optionName: metric_rbiaoyd8li8_cc8de8kb8e6
  groupby: []
  adhoc_filters: []
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title: RFM_Score
  x_axis_title_margin: 30
  y_axis_title: Customer ID
  y_axis_title_margin: 50
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: blueToGreen
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 14
query_context: '{"datasource":{"id":28,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"RFM_Score","label":"RFM_Score","expressionType":"SQL"}],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Customer
  ID","description":null,"expression":null,"filterable":true,"groupby":true,"id":796,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"uuid":"75432ce5-0b00-4efa-b993-b6e2a028217b","verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(Customer
  ID)","optionName":"metric_rbiaoyd8li8_cc8de8kb8e6"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Customer
  ID","description":null,"expression":null,"filterable":true,"groupby":true,"id":796,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"uuid":"75432ce5-0b00-4efa-b993-b6e2a028217b","verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(Customer
  ID)","optionName":"metric_rbiaoyd8li8_cc8de8kb8e6"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["RFM_Score"],"columns":[],"aggregates":{"COUNT(Customer
  ID)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"28__table","viz_type":"echarts_timeseries_bar","x_axis":"RFM_Score","metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Customer
  ID","description":null,"expression":null,"filterable":true,"groupby":true,"id":796,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"uuid":"75432ce5-0b00-4efa-b993-b6e2a028217b","verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(Customer
  ID)","optionName":"metric_rbiaoyd8li8_cc8de8kb8e6"}],"groupby":[],"adhoc_filters":[],"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title":"RFM_Score","x_axis_title_margin":30,"y_axis_title":"Customer
  ID","y_axis_title_margin":50,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"blueToGreen","show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelInterval":"auto","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[14],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 5aad81d8-fa79-48b8-9d66-ce89a51e3cdc
version: 1.0.0
dataset_uuid: fea7fdbf-8688-4b03-bcd6-27b4d2c2ac62
