slice_name: Heat map day hour
description: null
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  datasource: 27__table
  viz_type: heatmap_v2
  slice_id: 126
  x_axis: Hour
  groupby: Weekday
  metric:
    aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: TotalPrice
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 795
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DOUBLE PRECISION
      type_generic: 0
      uuid: a3317392-9bab-46de-ac38-f282920ff4df
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(TotalPrice)
    optionName: metric_6knb0i30ls6_k3a8oyoqb6
    sqlExpression: null
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: InvoiceDate
  row_limit: 10000
  normalize_across: heatmap
  legend_type: continuous
  linear_color_scheme: superset_seq_1
  border_color:
    a: 1
    b: 0
    g: 0
    r: 0
  xscale_interval: -1
  yscale_interval: -1
  left_margin: auto
  bottom_margin: auto
  value_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  x_axis_time_format: smart_date
  show_legend: true
  show_percentage: true
  extra_form_data: {}
  dashboards:
  - 14
query_context: '{"datasource":{"id":27,"type":"table"},"force":false,"queries":[{"filters":[{"col":"InvoiceDate","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"Hour","label":"Hour","expressionType":"SQL"},"Weekday"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"TotalPrice","description":null,"expression":null,"filterable":true,"groupby":true,"id":795,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"uuid":"a3317392-9bab-46de-ac38-f282920ff4df","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(TotalPrice)","optionName":"metric_6knb0i30ls6_k3a8oyoqb6","sqlExpression":null}],"orderby":[],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"rank","options":{"metric":"SUM(TotalPrice)"}}]}],"form_data":{"datasource":"27__table","viz_type":"heatmap_v2","slice_id":126,"x_axis":"Hour","groupby":"Weekday","metric":{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"TotalPrice","description":null,"expression":null,"filterable":true,"groupby":true,"id":795,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"uuid":"a3317392-9bab-46de-ac38-f282920ff4df","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(TotalPrice)","optionName":"metric_6knb0i30ls6_k3a8oyoqb6","sqlExpression":null},"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"InvoiceDate"}],"row_limit":10000,"normalize_across":"heatmap","legend_type":"continuous","linear_color_scheme":"superset_seq_1","border_color":{"a":1,"b":0,"g":0,"r":0},"xscale_interval":-1,"yscale_interval":-1,"left_margin":"auto","bottom_margin":"auto","value_bounds":[null,null],"y_axis_format":"SMART_NUMBER","x_axis_time_format":"smart_date","show_legend":true,"show_percentage":true,"extra_form_data":{},"dashboards":[14],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 1b053c88-1438-4174-a096-37f38fb516ca
version: 1.0.0
dataset_uuid: dc522637-e365-4fd8-b259-4ee432ee1848
