slice_name: Top 10 Clients
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 27__table
  viz_type: echarts_timeseries_bar
  x_axis:
    label: Customer ID
    sqlExpression: '"Customer ID"'
    expressionType: SQL
  time_grain_sqla: P1D
  xAxisForceCategorical: false
  x_axis_sort: SUM(TotalPrice)
  x_axis_sort_asc: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: TotalPrice
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 795
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DOUBLE PRECISION
      type_generic: 0
      uuid: a3317392-9bab-46de-ac38-f282920ff4df
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(TotalPrice)
    optionName: metric_6uo47tpmlcj_2n7n0gs5g7e
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: InvoiceDate
  order_desc: true
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title: Customer ID
  x_axis_title_margin: 30
  y_axis_title: Sales
  y_axis_title_margin: 50
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: blueToGreen
  time_shift_color: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 14
query_context: '{"datasource":{"id":27,"type":"table"},"force":false,"queries":[{"filters":[{"col":"InvoiceDate","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","label":"Customer
  ID","sqlExpression":"\"Customer ID\"","expressionType":"SQL"}],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"TotalPrice","description":null,"expression":null,"filterable":true,"groupby":true,"id":795,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"uuid":"a3317392-9bab-46de-ac38-f282920ff4df","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(TotalPrice)","optionName":"metric_6uo47tpmlcj_2n7n0gs5g7e","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"TotalPrice","description":null,"expression":null,"filterable":true,"groupby":true,"id":795,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"uuid":"a3317392-9bab-46de-ac38-f282920ff4df","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(TotalPrice)","optionName":"metric_6uo47tpmlcj_2n7n0gs5g7e","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["Customer
  ID"],"columns":[],"aggregates":{"SUM(TotalPrice)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"sort","options":{"by":"SUM(TotalPrice)","ascending":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"27__table","viz_type":"echarts_timeseries_bar","x_axis":{"label":"Customer
  ID","sqlExpression":"\"Customer ID\"","expressionType":"SQL"},"time_grain_sqla":"P1D","xAxisForceCategorical":false,"x_axis_sort":"SUM(TotalPrice)","x_axis_sort_asc":true,"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"TotalPrice","description":null,"expression":null,"filterable":true,"groupby":true,"id":795,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"uuid":"a3317392-9bab-46de-ac38-f282920ff4df","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(TotalPrice)","optionName":"metric_6uo47tpmlcj_2n7n0gs5g7e","sqlExpression":null}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"InvoiceDate"}],"order_desc":true,"row_limit":10,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title":"Customer
  ID","x_axis_title_margin":30,"y_axis_title":"Sales","y_axis_title_margin":50,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"blueToGreen","time_shift_color":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelInterval":"auto","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[14],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 378eba50-0006-4c28-b91b-7a639b6b633a
version: 1.0.0
dataset_uuid: dc522637-e365-4fd8-b259-4ee432ee1848
